config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { sessions: "sessions" }, :skip => [:registrations]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  require 'sidekiq/web'

  mount Sidekiq::Web => '/sidekiq'

  resources :dashboards do

    collection do
      get :googleanalytics
      get :facebook
      get :excel
      get :exceldate
    end

  end

  root "dashboards#index"

end

app/views/layouts/_alert.html.erb
<% if flash[:notice] %>
    <div class="alert alert-info alert-dismissible" role="alert" style=" margin-bottom: 0; padding-top: 14px; padding-bottom: 9px; z-index: 10; position: fixed; width: 1250px;">
      <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
      <h4 style="text-align: center"><%= notice %></h4>
    </div>
<% end %>

<% if flash[:alert] %>
    <div class="alert alert-danger alert-dismissible" role="alert">
      <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
      <%= alert %>
    </div>
<% end %>

<script type="text/javascript">
$( document ).ready(function() {
  setTimeout(function(){ $(".alert").hide() },5000)
});
</script>

app/views/layouts/_navigation.html.erb
<nav class="navbar-default navbar-static-side" role="navigation">
	<div class="sidebar-collapse">
		<ul class="nav metismenu" id="side-menu">
			<li class="nav-header">
				<div class="dropdown profile-element">
					<span>
						<a href="/"><img src="<%= image_path('logo.png') %>" style="width:160px"></a>
					</span>
				</div>
				<div class="logo-element">
					<img src="<%= image_path('logo2.png') %>" style="width:60px">
				</div>
			</li>
			<li >
					<a href="/"><i class="fa fa-th-large"></i> <span class="nav-label">綜合分析</span></a>
			</li>
			<li >
				<%= link_to facebook_dashboards_path do %>
					<i class="fa fa-facebook-f"> </i> <span class="nav-label"> 粉專分析 </span>
				<% end %>
			</li>
			<li >
				<%= link_to googleanalytics_dashboards_path do %>
					<i class="fa fa-google"></i> <span class="nav-label"> 官網分析 </span>
				<% end %>
			</li>
			<li >
				<%= link_to excel_dashboards_path(format: :xls), target: "_blank" do %>
					<i class="fa fa-file-excel-o"></i> <span class="nav-label"> 資料下載 </span>
				<% end %>
			</li>
				<li >
				<a class="startTour">
					<i class="fa fa fa-play"></i> <span class="nav-label"> 使用教學 </span>
				</a>
			</li>
			<li >
				<%= link_to destroy_user_session_path, method: :delete do %>
					<i class="fa fa-sign-out"></i> <span class="nav-label" > 登出 </span>
				<% end %>
			</li>
		</ul>
	</div>
</nav>

<% content_for :javascript do %>

<script type="text/javascript">
$(function() {
	if ( window.location.href.indexOf("/dashboards/facebook") > -1 ) {
		// Instance the tour
		var tour = new Tour({
			steps: [{
				element: ".startTour",
				title: "使用教學開始！ ",
				content: "六步驟，介面操作快速上手：Ｄ",
				placement: "right",
			},
				{
					element: ".navbar-header",
					title: "版面控制按鈕",
					content: "點擊後可以縮小左側導覽列。",
					placement: "right",
				},{
					element: "#labelpagefansm",
					title: "顯示期間",
					content: "點擊按鈕會切換數據顯示期間。",
					placement: "right",
				},{
					element: "#switch",
					title: "總顯示期間",
					content: "一次切換網站數據顯示期間。",
					placement: "bottom",
				},{
					element: "#starttime",
					title: "起始日期與結束日期",
					content: "切換網站資料顯示期間（今天資料不能選取，選取期間必須大於一天），點擊右側GO按鈕會出現下載選取日期區間的Excel檔案。",
					placement: "left",
				},{
					element: "#facebooktitle",
					title: "圖表數值解釋",
					content: "點擊名稱查看圖表數值定義。",
					placement: "left",
				},{
					element: "#lineChartfansretention",
					title: "數據名稱",
					content: "點擊數據名稱後可以隱藏此數據於圖表中，再次點擊後會再次出現。",
					placement: "top",
				}
			]
		});
		
	} else if ( window.location.href.indexOf("/dashboards/googleanalytics") > -1 ) {
				// Instance the tour
		var tour = new Tour({
			steps: [{
				element: ".startTour",
				title: "使用教學開始！ ",
				content: "六步驟，介面操作快速上手：Ｄ",
				placement: "right",
			},
				{
					element: ".navbar-header",
					title: "版面控制按鈕",
					content: "點擊後可以縮小左側導覽列。",
					placement: "right",
				},{
					element: "#labelwebusersm",
					title: "顯示期間",
					content: "點擊按鈕會切換數據顯示期間。",
					placement: "right",
				},{
					element: "#switch",
					title: "總顯示期間",
					content: "一次切換網站數據顯示期間。",
					placement: "bottom",
				},{
					element: "#starttime",
					title: "起始日期與結束日期",
					content: "切換網站資料顯示期間（今天資料不能選取，選取期間必須大於一天），點擊右側GO按鈕會出現下載選取日期區間的Excel檔案。",
					placement: "left",
				},{
					element: "#googletitle",
					title: "圖表數值解釋",
					content: "點擊名稱查看圖表數值定義。",
					placement: "left",
				},{
					element: "#lineChartwebactivity",
					title: "數據名稱",
					content: "點擊數據名稱後可以隱藏此數據於圖表中，再次點擊後會再次出現。",
					placement: "top",
				}
			]
		});
		
	} else {
		// Instance the tour
		var tour = new Tour({
			steps: [{
				element: ".startTour",
				title: "使用教學開始！ ",
				content: "六步驟，介面操作快速上手：Ｄ",
				placement: "right",
			},
				{
					element: ".navbar-header",
					title: "版面控制按鈕",
					content: "點擊後可以縮小左側導覽列。",
					placement: "right",
				},{
					element: "#labelpagefansm",
					title: "顯示期間",
					content: "點擊按鈕會切換數據顯示期間。",
					placement: "right",
				},{
					element: "#switch",
					title: "總顯示期間",
					content: "一次切換網站數據顯示期間。",
					placement: "bottom",
				},{
					element: "#starttime",
					title: "起始日期與結束日期",
					content: "切換網站資料顯示期間（今天資料不能選取，選取期間必須大於一天），點擊右側GO按鈕會出現下載選取日期區間的Excel檔案。",
					placement: "left",
				},{
					element: "#emailtitle",
					title: "圖表數值解釋",
					content: "點擊名稱查看圖表數值定義。",
					placement: "left",
				},{
					element: "#lineChartfansretention",
					title: "數據名稱",
					content: "點擊數據名稱後可以隱藏此數據於圖表中，再次點擊後會再次出現。",
					placement: "top",
				}
			]
		});
	}


	// Initialize the tour
	tour.init();

	$('.startTour').click(function(){
			tour.restart();
			// Start the tour
			// tour.start();
	})
});

</script>

<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <title>Seindashboard</title>
  <link href="<%= image_path('logo3.png') %>" rel="shortcut icon" type="image/x-icon" />
  <!-- Main css styles -->
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <!-- Main javascript files -->
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>

<body class="<% if current_user %> <% else %> login <% end %>" >
  <!-- Wrapper-->
  <div id="wapper">
    <!-- Navigation -->
    <% if current_user %>
     <%= render 'layouts/navigation' %>
    <% end %>
    
    <!-- Page wraper -->
    <div id="<% if current_user %>page-wrapper<% end %>" class="gray-bg <%= @extra_class %>">
      <!-- Page wrapper -->
      <% if current_user %>
       <%= render 'layouts/topnavbar' %>
      <% end %>
      <!-- Main view  -->
      <%= yield %>

    </div>
    <!-- End page wrapper-->


  </div>
  <!-- End wrapper-->

  <!-- Include javascript per-view -->
  <!-- For demo purpose we include javascript in view but you can easily start SeedProject and organize it with Rails asset pipeline as you want -->
  <%= yield :javascript %>

</body>
</html>